// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: app/observatory/profile/config.proto

package profile

import (
	burst "github.com/xtls/xray-core/app/observatory/burst"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Observatory struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	Tag               string                  `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	SubjectSelector   []string                `protobuf:"bytes,2,rep,name=subject_selector,json=subjectSelector,proto3" json:"subject_selector,omitempty"`
	ProbeUrl          string                  `protobuf:"bytes,3,opt,name=probe_url,json=probeUrl,proto3" json:"probe_url,omitempty"`
	ProbeInterval     int64                   `protobuf:"varint,4,opt,name=probe_interval,json=probeInterval,proto3" json:"probe_interval,omitempty"`
	EnableConcurrency bool                    `protobuf:"varint,5,opt,name=enable_concurrency,json=enableConcurrency,proto3" json:"enable_concurrency,omitempty"`
	PingConfig        *burst.HealthPingConfig `protobuf:"bytes,6,opt,name=ping_config,json=pingConfig,proto3" json:"ping_config,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Observatory) Reset() {
	*x = Observatory{}
	mi := &file_app_observatory_profile_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observatory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observatory) ProtoMessage() {}

func (x *Observatory) ProtoReflect() protoreflect.Message {
	mi := &file_app_observatory_profile_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observatory.ProtoReflect.Descriptor instead.
func (*Observatory) Descriptor() ([]byte, []int) {
	return file_app_observatory_profile_config_proto_rawDescGZIP(), []int{0}
}

func (x *Observatory) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Observatory) GetSubjectSelector() []string {
	if x != nil {
		return x.SubjectSelector
	}
	return nil
}

func (x *Observatory) GetProbeUrl() string {
	if x != nil {
		return x.ProbeUrl
	}
	return ""
}

func (x *Observatory) GetProbeInterval() int64 {
	if x != nil {
		return x.ProbeInterval
	}
	return 0
}

func (x *Observatory) GetEnableConcurrency() bool {
	if x != nil {
		return x.EnableConcurrency
	}
	return false
}

func (x *Observatory) GetPingConfig() *burst.HealthPingConfig {
	if x != nil {
		return x.PingConfig
	}
	return nil
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Observatory   []*Observatory         `protobuf:"bytes,1,rep,name=observatory,proto3" json:"observatory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_app_observatory_profile_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_app_observatory_profile_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_app_observatory_profile_config_proto_rawDescGZIP(), []int{1}
}

func (x *Config) GetObservatory() []*Observatory {
	if x != nil {
		return x.Observatory
	}
	return nil
}

var File_app_observatory_profile_config_proto protoreflect.FileDescriptor

const file_app_observatory_profile_config_proto_rawDesc = "" +
	"\n" +
	"$app/observatory/profile/config.proto\x12!xray.core.app.observatory.profile\x1a\"app/observatory/burst/config.proto\"\x91\x02\n" +
	"\vObservatory\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12)\n" +
	"\x10subject_selector\x18\x02 \x03(\tR\x0fsubjectSelector\x12\x1b\n" +
	"\tprobe_url\x18\x03 \x01(\tR\bprobeUrl\x12%\n" +
	"\x0eprobe_interval\x18\x04 \x01(\x03R\rprobeInterval\x12-\n" +
	"\x12enable_concurrency\x18\x05 \x01(\bR\x11enableConcurrency\x12R\n" +
	"\vping_config\x18\x06 \x01(\v21.xray.core.app.observatory.burst.HealthPingConfigR\n" +
	"pingConfig\"Z\n" +
	"\x06Config\x12P\n" +
	"\vobservatory\x18\x01 \x03(\v2..xray.core.app.observatory.profile.ObservatoryR\vobservatoryBv\n" +
	" com.xray.app.observatory.profileP\x01Z1github.com/xtls/xray-core/app/observatory/profile\xaa\x02\x1cXray.App.Observatory.Profileb\x06proto3"

var (
	file_app_observatory_profile_config_proto_rawDescOnce sync.Once
	file_app_observatory_profile_config_proto_rawDescData []byte
)

func file_app_observatory_profile_config_proto_rawDescGZIP() []byte {
	file_app_observatory_profile_config_proto_rawDescOnce.Do(func() {
		file_app_observatory_profile_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_observatory_profile_config_proto_rawDesc), len(file_app_observatory_profile_config_proto_rawDesc)))
	})
	return file_app_observatory_profile_config_proto_rawDescData
}

var file_app_observatory_profile_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_observatory_profile_config_proto_goTypes = []any{
	(*Observatory)(nil),            // 0: xray.core.app.observatory.profile.Observatory
	(*Config)(nil),                 // 1: xray.core.app.observatory.profile.Config
	(*burst.HealthPingConfig)(nil), // 2: xray.core.app.observatory.burst.HealthPingConfig
}
var file_app_observatory_profile_config_proto_depIdxs = []int32{
	2, // 0: xray.core.app.observatory.profile.Observatory.ping_config:type_name -> xray.core.app.observatory.burst.HealthPingConfig
	0, // 1: xray.core.app.observatory.profile.Config.observatory:type_name -> xray.core.app.observatory.profile.Observatory
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_app_observatory_profile_config_proto_init() }
func file_app_observatory_profile_config_proto_init() {
	if File_app_observatory_profile_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_observatory_profile_config_proto_rawDesc), len(file_app_observatory_profile_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_observatory_profile_config_proto_goTypes,
		DependencyIndexes: file_app_observatory_profile_config_proto_depIdxs,
		MessageInfos:      file_app_observatory_profile_config_proto_msgTypes,
	}.Build()
	File_app_observatory_profile_config_proto = out.File
	file_app_observatory_profile_config_proto_goTypes = nil
	file_app_observatory_profile_config_proto_depIdxs = nil
}
